# Generated by Django 4.2.13 on 2026-08-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('status_changed', 'Status Changed'), ('assigned', 'Assigned'), ('commented', 'Commented'), ('member_added', 'Member Added'), ('member_removed', 'Member Removed'), ('project_created', 'Project Created'), ('task_created', 'Task Created')], db_index=True, max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'activity_activitylog',
                'ordering': ['-created_at'],
            },
        ),
    ]
